NEW: GraphQL 4 Compatibility
silverstripe/silverstripe-versioned pull request #308
Opened 2020-11-02 03:17 UTC by unclecheese

Moved from: https://github.com/silverstripe/silverstripe-versioned/pull/293

2020-11-11 00:39 UTC, chillu requested changes

2020-11-11 00:39 UTC, chillu commented on _config/graphql_schema.yml
> +    '*':
Adding this to all schemas by default encourages the use of previews in your implementation, but also increases the security surface of your API. Given it's non-trivial to opt out of this, I think we need to add more docs on an "opt out config"

2020-11-11 00:39 UTC, chillu commented on src/GraphQL/Resolvers/VersionFilters.php
> +        switch ($mode) {
I think this needs to check permissions before setting stages, it's functionally identical to `VersionedHTTPMiddleware` which does that (via `Versioned::can_choose_site_stage()`)

2020-11-11 00:39 UTC, chillu commented on src/GraphQL/Resolvers/VersionFilters.php
> +        switch ($mode) {
Same here, needs permission checks

2020-11-11 00:39 UTC, chillu commented on src/GraphQL/Resolvers/VersionFilters.php
> +                $liveTable = $baseTable . '_Live';
Should use `Versioned->stageTable()`

2020-11-11 00:39 UTC, chillu commented on src/GraphQL/Resolvers/VersionFilters.php
> +                    $draftTable = $baseTable . '_Draft';
Should use `Versioned->stageTable()`

2020-11-11 00:39 UTC, chillu commented on src/GraphQL/Resolvers/VersionedResolver.php
> +            return $object->VersionsList();
Is this paginated? Feels like we'd run into performance issues otherwise, objects can have a *lot* of versions. Can be a follow up enhancement ticket, not a blocker for the PR.

2020-11-11 23:04 UTC, chillu commented on tests/php/GraphQL/Plugins/VersionedReadTest.php
> +class VersionedReadTest extends SapphireTest
There's some autoloading warnings in the build: https://travis-ci.com/github/silverstripe/silverstripe-versioned/jobs/429504664#L649

2020-11-12 01:49 UTC, chillu commented on src/GraphQL/Resolvers/VersionFilters.php
> +        switch ($mode) {
Since this is pre-existing functionality, I've moved the discussion to https://github.com/silverstripe/silverstripe-versioned/issues/310

2020-11-12 01:49 UTC, chillu commented on src/GraphQL/Resolvers/VersionFilters.php
> +                $liveTable = $baseTable . '_Live';
https://github.com/silverstripe/silverstripe-versioned/issues/310

2020-11-12 01:49 UTC, chillu commented on src/GraphQL/Resolvers/VersionFilters.php
> +        switch ($mode) {
https://github.com/silverstripe/silverstripe-versioned/issues/310

2020-11-12 01:56 UTC, chillu commented on tests/php/GraphQL/Plugins/VersionedReadTest.php
> +class VersionedReadTest extends SapphireTest
Wider discussion at https://github.com/silverstripe/silverstripe-graphql/issues/282#issuecomment-725777083

2020-11-12 02:06 UTC, unclecheese commented on _graphql/enums.yml
> +  values:
This may be outdated. I see ALL_VERSIONS below. (It wasn't before, and was causing versioned-admin tests to fail)

2020-11-12 02:13 UTC, unclecheese commented on src/GraphQL/Resolvers/VersionedResolver.php
> +            return $object->VersionsList();
Yeah it's paginated here: https://github.com/silverstripe/silverstripe-versioned/blob/pulls/1/schemageddon/src/GraphQL/Plugins/VersionedDataObject.php#L102

2020-11-12 02:14 UTC, chillu commented on src/GraphQL/Resolvers/VersionedResolver.php
> +            return $object->VersionsList();
Pre-existing bug. Even if we implemented pagination here, we'd also need to find a way to use it in the UI - scope creep. See https://github.com/silverstripe/silverstripe-versioned-admin/issues/185

2020-11-12 04:17 UTC, unclecheese commented on _config/graphql_schema.yml
> +    '*':
Tracking: https://github.com/silverstripe/silverstripe-graphql/issues/320

2020-11-13 00:51 UTC, merged