Unset sort for subquery if we're using MS SQL database
silverstripe/silverstripe-versioned pull request #325
Opened 2021-02-23 12:04 UTC by t3hn0

Fix for issue #324 .

2021-02-23 15:10 UTC, t3hn0 commented
I'm not sure how to fix error with "codecov/patch" check.

2021-02-24 10:38 UTC, maxime-rainville requested changes
Thanks for reporting this issue and providing a fix. That's awesome.

If you implement the suggestions below, we can most likely get this merged.

`codecov/patch` is complaining because the the conditional logic you added never gets run since we don't test for MS SQL. Disabling sorting all the time should squash that warning.

2021-02-24 10:38 UTC, maxime-rainville commented on src/RecursivePublishable.php
> +        if (class_exists("SilverStripe\\MSSQL\\MSSQLSchemaManager")) {
I'd rather avoid having references to `SilverStripe\MSSQL\MSSQLSchemaManager` in a core module because the MSSql module is not supported.

Looking at the original query you put on the parent issue, I'm 95% that none of the other DB drivers will care about whether this sub query is sorted or not. If anything, removing the sorting on the sub query might speed things up a tiny little bit.

My suggestion is just remove all the conditional statement and disable sorting for all the DB Drivers. Maybe add a quick comment saying that we're removing the sorting because some DB drivers don't let you sort sub queries.


If the test are green than we can merge this one.

2021-02-24 10:38 UTC, maxime-rainville commented on src/RecursivePublishable.php
> +        $ownedSQL = $owner->getComponents($relationship);
Maybe rename this variable until you actually get it converted to an SQL string. Otherwise, you'll have a variable that start as a `DataList` and then gets assigned a string value later on.

```suggestion
        $ownedQuery = $owner->getComponents($relationship);
```

2021-02-24 10:38 UTC, maxime-rainville commented on src/RecursivePublishable.php
> +                $ownedSQL = $ownedSQL->dataQuery()->sort(null, null, true);
```suggestion
                $ownedQuery = $ownedQuery->dataQuery()->sort(null, null, true);
```

2021-02-24 10:38 UTC, maxime-rainville commented on src/RecursivePublishable.php
> +        $ownedSQL = $ownedSQL->sql($ownedParams);
```suggestion
        $ownedSQL = $ownedQuery->sql($ownedParams);
```

2021-02-24 11:31 UTC, t3hn0 commented on src/RecursivePublishable.php
> +                $ownedSQL = $ownedSQL->dataQuery()->sort(null, null, true);
I implemented your suggestion.

2021-02-24 11:32 UTC, t3hn0 commented on src/RecursivePublishable.php
> +        $ownedSQL = $ownedSQL->sql($ownedParams);
I implemented your suggestion.

2021-02-24 11:32 UTC, t3hn0 commented on src/RecursivePublishable.php
> +        if (class_exists("SilverStripe\\MSSQL\\MSSQLSchemaManager")) {
removed both conditionals and added comment about removing sort in sub queries.

2021-02-24 13:11 UTC, t3hn0 reviewed
Requested changes were implemented

2021-02-24 21:22 UTC, maxime-rainville approved these changes
Good stuff

2021-02-24 21:24 UTC, merged