Rescue Master Branch Commit ENH Prefer `::class` syntax over class strings
silverstripe/silverstripe-versioned pull request #372
Opened 2022-08-26 01:36 UTC by GuySartorelli

Rescues and extends https://github.com/silverstripe/silverstripe-versioned/commit/43be1a09235507eb8472f1dc70d5586240ef145c

There's no change to API here so it makes sense to target `1` so both major lines can benefit.

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10350

2022-08-29 06:13 UTC, emteknetnz requested changes
This looks quite different from the rescued commit?

2022-08-29 21:12 UTC, GuySartorelli commented
This PR rescues "and expands upon" the original PR.
I cherry-picked in the commit from the original PR and then looked for instances of what the original commit was doing which had been either missed or added since the original commit was created. The PR would be incomplete if these additional items were left unchanged, since the purpose is to update the old hardcoded string syntax.

2022-08-31 21:38 UTC, emteknetnz requested changes

2022-08-31 21:38 UTC, emteknetnz commented on lang/en.yml
> +    Unpublished: 'Unpublished {name} {title}'
We can remove this?

2022-08-31 22:51 UTC, GuySartorelli commented on lang/en.yml
> +    Unpublished: 'Unpublished {name} {title}'
Yeah. Not sure why that was being added in that commit - I had assumed it was in the wrong place originally and that this was the new place but now that I'm doing a search for it, it was definitely already in the right place. I'll remove this.

2022-08-31 22:51 UTC, GuySartorelli commented on lang/en.yml
> +    Unpublished: 'Unpublished {name} {title}'
Done

2022-09-01 02:48 UTC, emteknetnz approved these changes

2022-09-01 02:49 UTC, merged