API Remove deprecated code
silverstripe/silverstripe-versioned pull request #381
Opened 2022-11-28 03:25 UTC by sabina-talipova

### Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10501

2022-12-05 22:30 UTC, emteknetnz requested changes

2022-12-05 22:30 UTC, emteknetnz commented on src/Versioned.php
> -        // Disallow $createNewVersion = false
Remove the $createNewVersion param

2022-12-06 01:10 UTC, sabina-talipova commented on src/Versioned.php
> -        // Disallow $createNewVersion = false
Done

2022-12-07 21:26 UTC, emteknetnz approved these changes

2022-12-07 21:45 UTC, merged