Add canPublish check for ChangeSet
silverstripe/silverstripe-versioned pull request #384
Opened 2022-11-30 07:48 UTC by mark-a-j-adriano

Maybe the solution for https://github.com/silverstripe/silverstripe-versioned/issues/383

2022-11-30 10:08 UTC, kinglozzer commented on src/ChangeSetItem.php
> +                if ($object->canPublish($member)) {
We shouldn’t add this kind of logic here, as it’ll potentially block programatic publishing (e.g. a CLI task where no user is logged in)

2022-11-30 10:08 UTC, kinglozzer requested changes

2022-11-30 10:08 UTC, kinglozzer commented on src/ChangeSetItem.php
> +                if ($object->canPublish($member)) {
We shouldn’t add this kind of logic here, as it’ll potentially block programatic publishing (e.g. a CLI task where no user is logged in)

2022-11-30 11:19 UTC, michalkleiner commented
`ChangeSetItem` already has its own [`canPublish` method ](https://github.com/silverstripe/silverstripe-versioned/blob/1/src/ChangeSetItem.php#L403) that checks the record object's canPublish, so it must be something else going on (if something is actually going on).

2022-11-30 11:50 UTC, mark-a-j-adriano commented on src/ChangeSetItem.php
> +                if ($object->canPublish($member)) {
> `ChangeSetItem` already has its own [`canPublish` method ](https://github.com/silverstripe/silverstripe-versioned/blob/1/src/ChangeSetItem.php#L403) that checks the record object's canPublish, so it must be something else going on (if something is actually going on).

Nope, `ChangeSetItem` canPublish method is **not** called.  https://github.com/silverstripe/silverstripe-versioned/blob/4baa7b48298c18617c2efc1ea5cf912af62de414/src/ChangeSetItem.php#L307
Already acts on the asset

2022-11-30 11:52 UTC, mark-a-j-adriano commented on src/ChangeSetItem.php
> +                if ($object->canPublish($member)) {
@kinglozzer -> not sure where to put the logic if it is not the correct place. (In our use case this might suffice)

2022-11-30 11:57 UTC, kinglozzer commented on src/ChangeSetItem.php
> +                if ($object->canPublish($member)) {
I think for your use case I’d probably remove the image from `$owns` and add some logic in `onAfterPublish()` to check the date and publish if applicable

2022-11-30 22:31 UTC, michalkleiner commented on src/ChangeSetItem.php
> +                if ($object->canPublish($member)) {
That would be a workaround for Mark, but I think this is a legit bug where it is reasonable to anticipate the permissions are respected, or we openly document that ownership cascade publishing trumps individual object permissions.

2022-11-30 22:45 UTC, GuySartorelli commented on src/ChangeSetItem.php
> +                if ($object->canPublish($member)) {
> I think this is a legit bug where it is reasonable to anticipate the permissions are respected

I agree

2022-12-01 09:18 UTC, kinglozzer commented on src/ChangeSetItem.php
> +                if ($object->canPublish($member)) {
Yep sorry I meant as a workaround! Will post my thoughts in the issue #383

2023-10-02 22:55 UTC, GuySartorelli commented
I'm going to close this PR for now. As mentioned in the issue, this can't be resolved until we're ready to start working on a new major release.
The closed PR will still be associated with and linked from the issue, which is already in the CMS 6 milestone, so when we start working on that we'll have access to this PR to reference as a potential solution.

2023-10-02 22:55 UTC, closed without merging