FIX Ensure sort is not empty
silverstripe/silverstripe-versioned pull request #385
Opened 2022-12-05 02:29 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/10449

Requires https://github.com/silverstripe/silverstripe-framework/pull/10600 to be merged first - but this was run though an installer CI run: https://github.com/emteknetnz/silverstripe-installer/actions/runs/3617074332

2022-12-05 04:37 UTC, michalkleiner commented on src/Versioned.php
> +            $list = $list->where($filter);
Can we use `filter` in line with the other work related to replacing where with filter?

```suggestion
            $list = $list->filter($filter);
```

2022-12-05 22:14 UTC, GuySartorelli requested changes

2022-12-05 22:14 UTC, GuySartorelli commented on src/Versioned.php
> +            $list = $list->orderBy($sort);
Is `orderBy()` correct here? What passes raw SQL into this method?

If it's just something passing in `"Table"."Column"` syntax then we should probably either a) consider allowing that syntax in `sort()` (it's fairly common and isn't vulnerable to sql injection attacks) or b) reformat the value, for example by excluding the table name, depending on what exactly is being passed in from where.

2022-12-05 23:04 UTC, emteknetnz commented on src/Versioned.php
> +            $list = $list->orderBy($sort);
The "migration" is to use orderBy() so that existing raw sql still works, though change it to sort() if it's easy enough.  To me, this is a hard migration so I think orderBy() is ok here, though obviously I'd prefer sort()

a) would is basically new functionality on DataList::sort() and would requires a new card IMO since there's a whole lot of validating that tables exist etc. I have no idea what happens for instance when joining tables where the there is a $table_name that doesn't match the Model class name for instance.

b) Is just a) - handling table names

In terms of where the $sort param is actually used, outside of unit tests, it's only Hierarchy.php

```php
        $baseTable = $owner->baseTable();
        $parentIDColumn = $owner->getSchema()->sqlColumnForField($owner, 'ParentID');
        return Versioned::get_including_deleted(
            $owner->baseClass(),
            [ $parentIDColumn => $owner->ID ],
            "\"{$baseTable}\".\"ID\" ASC"
        );
```

I'm not sure how I refactor this to sort() the results by `"{$baseTable}"."ID" ASC"` - where $baseTable is the mysql table name

2022-12-05 23:06 UTC, emteknetnz commented on src/Versioned.php
> +            $list = $list->where($filter);
That should be done as part of this issue - https://github.com/silverstripe/silverstripe-framework/issues/10601

2022-12-06 03:22 UTC, emteknetnz commented on src/Versioned.php
> +            $list = $list->orderBy($sort);
Based on [notation clarification](https://github.com/silverstripe/silverstripe-framework/pull/10600#discussion_r1040323455) - we need orderBy() here

2022-12-06 21:04 UTC, GuySartorelli approved these changes

2022-12-06 21:04 UTC, GuySartorelli commented
Looks good.
Will merge when silverstripe/framework#10449 is ready to merge

2022-12-07 01:12 UTC, merged