MNT Update tests to not expect trailing slash
silverstripe/silverstripe-versioned pull request #388
Opened 2023-01-13 00:03 UTC by GuySartorelli

https://github.com/silverstripe/silverstripe-framework/pull/10538 makes various methods _not_ include a trailing slash by default. This PR updates relevant tests to not expect trailing slashes.

## Parent issue
- https://github.com/silverstripe/silverstripe-cms/issues/2780

2023-01-18 22:23 UTC, emteknetnz approved these changes
Don't think this needs to be a draft PR

2023-01-18 22:24 UTC, emteknetnz requested changes
Oh - there's failing unit tests - I guess those will be resolved once the framework PR is merged

2023-01-18 22:25 UTC, GuySartorelli commented
Correct, it doesn't need to be draft. My bad.
Relevant failing unit tests are not failing in installer CI (see main issue)

2023-01-20 02:22 UTC, emteknetnz approved these changes

2023-01-20 02:30 UTC, GuySartorelli commented
Remaining failing unit tests are unrelated.

2023-01-20 02:31 UTC, merged