MNT Remove TODO comments
silverstripe/silverstripe-versioned pull request #418
Opened 2023-10-10 01:55 UTC by sabina-talipova

## Parent issue
- https://github.com/silverstripe/.github/issues/116

2023-10-10 01:57 UTC, sabina-talipova commented on src/Versioned.php
> -     * @todo Performance - could do this directly via SQL.
It looks like an additional way for better performance.

2023-10-10 01:57 UTC, sabina-talipova commented on src/RecursivePublishable.php
> -        // @todo - Cache this more intelligently
It looks like a small warning.

2023-10-19 01:48 UTC, sabina-talipova commented on src/DataDifferencer.php
> -        // not playing nice with mocked images
Open ticket: https://github.com/silverstripe/silverstripe-versioned/issues/414

2023-10-19 01:48 UTC, sabina-talipova commented on tests/php/DataDifferencerTest.php
> -        // an array-based value in the first place.
Open ticket: https://github.com/silverstripe/silverstripe-versioned/issues/413

2023-10-19 01:49 UTC, sabina-talipova commented on src/ChangeSet.php
> -            // TODO: Handle case of implicit added item being removed.
Open ticket: https://github.com/silverstripe/silverstripe-versioned/issues/415

2023-10-19 01:49 UTC, sabina-talipova commented on src/RecursivePublishableHandler.php
> -     * @todo Build this action into explicit UX action: https://github.com/silverstripe/silverstripe-versioned/issues/71
Open ticket: https://github.com/silverstripe/silverstripe-versioned/issues/416

2023-10-19 01:50 UTC, sabina-talipova commented on src/Versioned.php
> -            // @todo - This method doesn't exist on DataList
Open ticket: https://github.com/silverstripe/silverstripe-versioned/issues/417

2023-10-19 22:20 UTC, GuySartorelli requested changes

2023-10-19 22:20 UTC, ChloeSartorelli commented on src/RecursivePublishable.php
> +        // Cache this more intelligently
```suggestion
```
This was a todo comment that suggested that the current caching mechanism wasn't sufficient. We probably don't need an issue for this one, just remove it.

2023-10-19 22:20 UTC, ChloeSartorelli commented on src/RecursivePublishableHandler.php
> -     * @todo Build this action into explicit UX action: https://github.com/silverstripe/silverstripe-versioned/issues/71
This was closed 👍

2023-10-19 22:20 UTC, GuySartorelli commented on src/Versioned.php
> +     * Performance - could do this directly via SQL.
```suggestion
```
This was a todo comment saying that this could be done another way, and implying that someone should investigate that. We don't need an issue for this one but be should remove it.

2023-10-26 20:53 UTC, sabina-talipova commented on src/RecursivePublishable.php
> +        // Cache this more intelligently
Updated

2023-10-26 20:55 UTC, sabina-talipova commented on src/Versioned.php
> +     * Performance - could do this directly via SQL.
Updated

2023-10-29 23:15 UTC, GuySartorelli approved these changes
LGTM

2023-10-29 23:16 UTC, merged