FIX Remove implicitly added item
silverstripe/silverstripe-versioned pull request #423
Opened 2023-10-24 03:51 UTC by sabina-talipova

## Description
Implicitly added item to the ChangeSet cannot be remove if explicitly added parent item was removed and ChangeSet has State = 'published'. I think we should update versioned object state even if object was already published.   

## Parent issue
- https://github.com/silverstripe/silverstripe-versioned/issues/422

2023-10-26 21:48 UTC, maxime-rainville requested changes
That's an elegant solution. I'm just thinking we should add a few extra scenarios in the test coverage.

2023-10-26 21:48 UTC, maxime-rainville commented on tests/php/ChangeSetTest.php
> +
Can we add a `assertChangeSetLooksLike` assertion here that `mid1` and `end1` are alse part of the changeset before we remove them?

2023-10-26 21:48 UTC, maxime-rainville commented on tests/php/ChangeSetTest.php
> +    }
Can we add two extra test cases:
- Item A and Item B both reference Item C. Item A is removed from changeset. Item C should still be in the changeset.
- Item D references Item E. Item D and Item E are both explicitly added to changeset. Removing Item D should not remove Item E.

From the UI testing I've done, both those test case seem to behave as expected. It's just a question of making sure they are covered by Unit test.

2023-10-27 02:23 UTC, sabina-talipova commented on tests/php/ChangeSetTest.php
> +
Updated

2023-10-27 02:23 UTC, sabina-talipova commented on tests/php/ChangeSetTest.php
> +    }
Updated

2023-10-27 03:23 UTC, michalkleiner commented on src/ChangeSet.php
> +                if (!array_key_exists($objectKey, $implicit ?? [])) {
Null coalescing fallback not needed here as `calculateImplicit` should return an array already. If not, it should be added there rather than here.

```suggestion
                if (!array_key_exists($objectKey, $implicit)) {
```

2023-10-27 03:57 UTC, sabina-talipova commented on src/ChangeSet.php
> +                if (!array_key_exists($objectKey, $implicit ?? [])) {
Updated

2023-10-30 08:35 UTC, maxime-rainville requested changes
Consider adding an optional `$message` parameter to the `assertChangeSetLooksLike` helper method. That could help make the test more readable. 

You could provide assumption like:
- Removing an explicitly defined ChangeSetItem removes all its implicit ChangeSetItems.
- Removing an explicitly defined ChangeSetItem does not remove its implicit ChangeSetItem if that item is also referenced by another a third one.
- Removing an explicitly defined ChangeSetItem does not remove its implicit ChangeSetItem if that item is also explicitly added to the changeset

This is more in the nice to have category.

2023-10-30 08:35 UTC, maxime-rainville commented on tests/php/ChangeSetTest.php
> +        $changeset->addObject($end1); // Item end1 explisitly added to ChangeSet
```suggestion
        $changeset->addObject($end1); // Item end1 explicitly added to ChangeSet
```

2023-10-30 08:35 UTC, maxime-rainville commented on tests/php/ChangeSetTest.php
> +    public function testRemoveObject()
Personally, I would have broken up this method into 3 different tests just so we can better see what is being tested. But I'm not fuss about it.

2023-10-30 20:14 UTC, sabina-talipova commented on tests/php/ChangeSetTest.php
> +    public function testRemoveObject()
Updated

2023-10-30 20:14 UTC, sabina-talipova commented on tests/php/ChangeSetTest.php
> +        $changeset->addObject($end1); // Item end1 explisitly added to ChangeSet
Updated

2023-11-01 03:01 UTC, maxime-rainville approved these changes
LGTM

2023-11-01 03:01 UTC, merged