FIX ModelAdmin toast elements
silverstripe/silverstripe-versioned pull request #424
Opened 2023-11-01 22:06 UTC by sabina-talipova

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1544

2023-11-02 21:10 UTC, GuySartorelli requested changes

2023-11-02 21:10 UTC, GuySartorelli commented on lang/en.yml
> +    PUBLISHEDTOASTMESSAGE: 'Published {name} {title}'
```suggestion
    PUBLISHEDTOASTMESSAGE: 'Published {type} ''{title}''.'
```
As per the changes in the framework PR. Please also apply to the instance of this in PHP code.

2023-11-02 21:12 UTC, GuySartorelli requested changes

2023-11-02 21:12 UTC, GuySartorelli commented on lang/en.yml
>      Unpublished: 'Unpublished {name} {title}'
Please update these to have `''` around the title. Don't change `name` to `type` here since this is a pre-existing translation string.
You can reuse the existing translation key for this, since we're not changing the wording, meaning, word order, or variable names.

2023-11-03 00:22 UTC, sabina-talipova commented on lang/en.yml
> +    PUBLISHEDTOASTMESSAGE: 'Published {name} {title}'
Updated

2023-11-03 00:26 UTC, sabina-talipova commented on lang/en.yml
>      Unpublished: 'Unpublished {name} {title}'
Updated

2023-11-07 02:30 UTC, GuySartorelli approved these changes
LGTM - will merge when other PRs are all ready to merge.

2023-11-07 21:48 UTC, sabina-talipova commented on src/VersionedGridFieldItemRequest.php
> +        $controller->getResponse()->addHeader('X-Status', $message);
Replaced with `$controller->getResponse()`.

2023-11-07 21:48 UTC, sabina-talipova commented on src/VersionedGridFieldItemRequest.php
> +        $controller->getResponse()->addHeader('X-Status', $message);
Replaced with `$controller->getResponse()`.

2023-11-07 21:48 UTC, sabina-talipova commented on src/VersionedGridFieldItemRequest.php
> +        $controller->getResponse()->addHeader('X-Status', $message);
Replaced with `$controller->getResponse()`.

2023-11-09 20:46 UTC, GuySartorelli approved these changes
Looks good again. Will merge when other PRs are ready.

2023-11-12 20:44 UTC, GuySartorelli approved these changes
Looks great and works well locally.

2023-11-12 20:45 UTC, merged