API Deprecate Versioned() having parameter
silverstripe/silverstripe-versioned pull request #425
Opened 2023-11-03 01:23 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-versioned/issues/417

Currently this parameter is used and if called could cause a hard error since the having() method doesn't exist on DataList

I'm not even sure why this paramater ever existed since I'm not sure how it could even be used in this context since you're calling DataList::get() and then passing through the $filter, $sort, $limit and $join paramaters ... though there doesn't seem like there's anyway to even use having since it's not creating a select SQL statement with an aggregate function like `count()` in it

Seems best to just prevent it from even attempting to call the non-existant DataList::having() and deprecate it

2023-11-03 22:52 UTC, GuySartorelli commented
This wasn't one of the options discussed in refinement. Why not implement having on datalist, or use `alterDataQuery` to call having on the underlying `DataQuery`?

2023-11-05 20:16 UTC, emteknetnz commented
Having a better look at this now seems like this param on Versions() that shouldn't have even be there in the first place

2023-11-05 22:20 UTC, GuySartorelli requested changes
Need to target `2`. We don't deprecate API in patch releases.

Not super happy with this approach but it's an improvement on what we had, since it's not throwing an error any time someone tries to use the parameter now - so I'll be okay with it when it's targetting the `2` branch.

2023-11-05 22:33 UTC, emteknetnz commented
@GuySartorelli done

2023-11-05 23:45 UTC, GuySartorelli approved these changes
LGTM

2023-11-05 23:46 UTC, merged