ENH Respect new has_one config
silverstripe/silverstripe-versioned pull request #427
Opened 2023-12-04 04:51 UTC by GuySartorelli

`has_one` can now optionally have an array configuration to allow supporting multiple reciprocal `has_many` in a single `has_one` relation.

Note that a dependency bump is required since this is calling a new method. Tests won't be green until https://github.com/silverstripe/silverstripe-framework/pull/11084 is merged but an installer CI run is linked in the issue.

## PRs
- https://github.com/silverstripe/silverstripe-linkfield/issues/5

2023-12-07 01:21 UTC, emteknetnz reviewed
Seems fine, won't approve just yet, will approve when other PRs are approved

2023-12-11 21:18 UTC, emteknetnz approved these changes

2023-12-11 21:19 UTC, emteknetnz requested changes
Could you trigger a rebuild now the framework PR has been merged

2023-12-11 21:35 UTC, GuySartorelli commented
Done (FYI you can just re-run the existing CI when it's dependent on another PR being merged - no need for pushing or anything like that)

2023-12-12 01:14 UTC, emteknetnz approved these changes

2023-12-12 01:15 UTC, merged