ENH Add generic types
silverstripe/silverstripe-versioned pull request #431
Opened 2024-01-11 02:41 UTC by GuySartorelli

Requires https://github.com/silverstripe/silverstripe-framework/pull/11108 for these generics to take effect.

## Issue
- https://github.com/silverstripe/silverstripe-framework/issues/11066

2024-01-18 21:20 UTC, emteknetnz requested changes

2024-01-18 21:20 UTC, emteknetnz commented on src/Versioned.php
> + * @extends DataExtension<DataObject&RecursivePublishable&Versioned>
```suggestion
 * @extends DataExtension<DataObject&RecursivePublishable&static>
```

2024-01-18 21:20 UTC, emteknetnz commented on src/Versioned.php
> +     * @return T&Versioned
```suggestion
     * @return T&static
```

2024-01-18 21:20 UTC, emteknetnz commented on src/Versioned.php
> +     * @return T&Versioned
```suggestion
     * @return T&static
```

2024-01-18 21:20 UTC, emteknetnz commented on src/VersionedStateExtension.php
> + * @extends Extension<T>
```suggestion
 * @extends Extension<RequestHandler|DataObject>
```
Wouldn't this do the same thing?

2024-01-18 22:27 UTC, GuySartorelli commented on src/VersionedStateExtension.php
> + * @extends Extension<T>
Nope. Having the `@template T` there means subclasses can say "Use my type instead" using `@extends`.
`VersionedTestSessionExtension` is a subclass of `VersionedStateExtension` and has its own type, so `VersionedStateExtension` has to use `@template T` to allow that to happen.

2024-01-18 22:27 UTC, GuySartorelli commented on src/Versioned.php
> +     * @return T&Versioned
Done

2024-01-18 22:27 UTC, GuySartorelli commented on src/Versioned.php
> +     * @return T&Versioned
Done

2024-01-18 22:27 UTC, GuySartorelli commented on src/Versioned.php
> + * @extends DataExtension<DataObject&RecursivePublishable&Versioned>
Done

2024-01-19 04:07 UTC, emteknetnz approved these changes

2024-01-19 04:07 UTC, merged