API Deprecate Versioned::canArchive()
silverstripe/silverstripe-versioned pull request #461
Opened 2024-08-13 23:29 UTC by GuySartorelli

For versioned records, there is no concept of "deleting" the record - it's either being archived, unpublished, or in rare cases removed from draft but left published.

Previously the `canDelete()` method has been used to check if a record can be removed from draft specifically for versioned records - which is such a rare edge case it almost doesn't bare thinking about, especially given there's no way to do that purely by interacting with the UI, nor with the web API endpoints available in core or supported modules.

Instead, `canDelete()` should be used to check if the record can be archived. This reduces cognitive load for developers and is a step towards simplifying the overly-complex versioning system. This is also in keeping with other mechanisms, such as `cascade_deletes` which cascades archiving for versioned records.

## Issue
- https://github.com/silverstripe/silverstripe-versioned/issues/447

2024-08-13 23:29 UTC, GuySartorelli commented on src/Versioned.php
> +        $extended = Deprecation::withNoReplacement(fn() => $owner->extendedCan('canArchive', $member));
`extendedCan()` will result in calling `extendCanArchive()` which is also deprecated, so we need to wrap this call too.

2024-08-13 23:30 UTC, GuySartorelli commented on src/Versioned.php
> +        Deprecation::notice('5.3.0', 'Will be removed without equivalent functionality.');
`protected` methods are part of our [definition of public API](https://docs.silverstripe.org/en/5/project_governance/public_api/) so we need to deprecate this even though nobody is likely to be calling it directly and it's effectively a no-op.

2024-08-14 03:01 UTC, emteknetnz requested changes

2024-08-14 03:01 UTC, emteknetnz commented on src/GridFieldArchiveAction.php
> +            if (!Deprecation::withNoReplacement(fn() => $item->canArchive())) {
```suggestion
            $canArchive = Deprecation::withNoReplacement(fn() => $item->canArchive());
            if (!canArchive) {
```
Makes this a lot easier to read

Also update all other instances in this PR

2024-08-14 03:13 UTC, GuySartorelli commented on src/GridFieldArchiveAction.php
> +            if (!Deprecation::withNoReplacement(fn() => $item->canArchive())) {
That's very subjective and I personally don't agree, but I'll make the change to avoid ping pong.

2024-08-14 03:22 UTC, GuySartorelli commented on src/GridFieldArchiveAction.php
> +            if (!Deprecation::withNoReplacement(fn() => $item->canArchive())) {
Done, fingers cross I caught them all

2024-08-14 03:34 UTC, GuySartorelli commented on src/GridFieldArchiveAction.php
> +        if ($canArchive) {
Had to separate these conditions to comply with https://github.com/silverstripe/silverstripe-versioned/pull/461#discussion_r1716249601

2024-08-14 06:41 UTC, emteknetnz requested changes

2024-08-14 06:41 UTC, emteknetnz commented on src/GridFieldArchiveAction.php
> +            if ($canArchive) {
```suggestion
            $canArchive = Deprecation::withNoReplacement(fn() => $item->canArchive());
            if (!$canArchive) {
```

2024-08-14 06:41 UTC, emteknetnz commented on src/GridFieldArchiveAction.php
> +        if ($canArchive) {
```suggestion
        $canArchive = Deprecation::withNoReplacement(fn() => $record->canArchive());
        if (!$canArchive) {
```

2024-08-15 00:20 UTC, GuySartorelli commented on src/GridFieldArchiveAction.php
> +            if ($canArchive) {
Oops! Done

2024-08-15 00:20 UTC, GuySartorelli commented on src/GridFieldArchiveAction.php
> +        if ($canArchive) {
Oops! Done

2024-08-15 01:55 UTC, emteknetnz approved these changes

2024-08-15 01:59 UTC, merged